
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentalski?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+3
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
  http:
    encoding:
      charset: cp857
      enabled: true
      force: true
server:
  port: 80
